get_name: ram2p
get_keyword: #
get_keyword: (
get_keyword: parameter
get_name: DEPTH
get_keyword: =
get_value: 256
get_choice: ,
get_keyword: parameter
get_name: AWID
get_keyword: =
get_value: 8
get_choice: ,
get_keyword: parameter
get_name: DWID
get_keyword: =
get_value: 16
get_choice: )
get_keyword: (
